export * from './my-orders/my-orders.component'
export * from './my-products/my-products.component'
export * from './my-settings/my-settings.component'
export * from './my-home/my-home.component'
export * from './kitchen-menu/kitchen-menu.component'